### ISSUE TITLE
Access to website settings

### ISSUE THREAD

**Issue by lucode** [shingonoide/odoo_ezdoo#1]
Maybe you could change the habit that your module is hiding website settings from other admins then the superadmin? Thank you

**Comment by shingonoide** [comment]
Habits, WFT?

I guess you trying to talk about some bug, could you please be more polite and create a real issue here to be revolved.

Thanks!

**Comment by shingonoide** [comment]
Sorry @lucode I can't find any bug as you mentioned so far.
If you still has any issue, please create a new issue.
Thanks for trying reporting something.
